import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import time
from datetime import datetime
from matplotlib.animation import FuncAnimation, PillowWriter
OBD_PIDS = {
    0x00: "PIDs supported [01-20]",
    0x01: "Monitor status this drive",
    0x02: "Freeze DTC",
    0x03: "Fuel system status",
    0x04: "Calculated engine load",
    0x05: "Engine coolant temperature",
    0x06: "Short term fuel trim bank 1",
    0x07: "Long term fuel trim bank 1",
    0x08: "Short term fuel trim bank 2",
    0x09: "Long term fuel trim bank 2",
    0x0A: "Fuel pressure",
    0x0B: "Intake manifold absolute pressure",
    0x0C: "Engine RPM",
    0x0D: "Vehicle speed",
    0x0E: "Timing advance",
    0x0F: "Intake air temperature",
    0x10: "MAF air flow rate",
    0x11: "Throttle position",
    0x12: "Commanded secondary air status",
    0x13: "Oxygen sensors present",
    0x14: "Oxygen sensor 1",
    0x15: "Oxygen sensor 2",
    0x16: "Oxygen sensor 3",
    0x17: "Oxygen sensor 4",
    0x18: "Oxygen sensor 5",
    0x19: "Oxygen sensor 6",
    0x1A: "Oxygen sensor 7",
    0x1B: "Oxygen sensor 8",
    0x1C: "OBD standards this vehicle conforms to",
    0x1D: "Oxygen sensors present",
    0x1E: "Auxiliary input status",
    0x1F: "Run time since engine start",
    0x20: "PIDs supported [21-40]",
    0x21: "Distance traveled with malfunction indicator lamp (MIL) on",
    0x22: "Fuel rail pressure (diesel, or gasoline direct injection)",
    0x23: "Fuel rail gauge pressure (diesel, or gasoline direct injection)",
    0x24: "Oxygen sensor 1",
    0x25: "Oxygen sensor 2",
    0x26: "Oxygen sensor 3",
    0x27: "Oxygen sensor 4",
    0x28: "Oxygen sensor 5",
    0x29: "Oxygen sensor 6",
    0x2A: "Oxygen sensor 7",
    0x2B: "Oxygen sensor 8",
    0x2C: "Commanded EGR",
    0x2D: "EGR error",
    0x2E: "Commanded evaporative purge",
    0x2F: "Fuel tank level input",
    0x30: "Warmups since codes cleared",
    0x31: "Distance traveled since codes cleared",
    0x32: "Evap system vapor pressure",
    0x33: "Barometric pressure",
    0x34: "Oxygen sensor 1",
    0x35: "Oxygen sensor 2",
    0x36: "Oxygen sensor 3",
    0x37: "Oxygen sensor 4",
    0x38: "Oxygen sensor 5",
    0x39: "Oxygen sensor 6",
    0x3A: "Oxygen sensor 7",
    0x3B: "Oxygen sensor 8",
    0x3C: "Catalyst temperature bank 1, sensor 1",
    0x3D: "Catalyst temperature bank 1, sensor 2",
    0x3E: "Catalyst temperature bank 2, sensor 1",
    0x3F: "Catalyst temperature bank 2, sensor 2",
    0x40: "PIDs supported [41-60]",
    0x41: "Monitor status this drive",
    0x42: "Control module voltage",
    0x43: "Absolute load value",
    0x44: "Commanded air-fuel ratio",
    0x45: "Relative throttle position",
    0x46: "Ambient air temperature",
    0x47: "Absolute throttle position B",
    0x48: "Absolute throttle position C",
    0x49: "Accelerator pedal position D",
    0x4A: "Accelerator pedal position E",
    0x4B: "Accelerator pedal position F",
    0x4C: "Commanded throttle actuator",
    0x4D: "Time run with MIL on",
    0x4E: "Time since trouble codes cleared",
    0x4F: "Maximum value for fuel-air equivalence ratio",
    0x50: "Maximum value for air flow rate from mass air flow sensor",
    0x51: "Fuel type",
    0x52: "Ethanol fuel %",
    0x53: "Absolute Evap system vapor pressure",
    0x54: "Evap system vapor pressure",
    0x55: "Short term secondary oxygen sensor trim bank 1",
    0x56: "Long term secondary oxygen sensor trim bank 1",
    0x57: "Short term secondary oxygen sensor trim bank 2",
    0x58: "Long term secondary oxygen sensor trim bank 2",
    0x59: "Fuel rail absolute pressure",
    0x5A: "Relative accelerator pedal position",
    0x5B: "Hybrid battery pack remaining life",
    0x5C: "Engine oil temperature",
    0x5D: "Fuel injection timing",
    0x5E: "Engine fuel rate",
    0x5F: "Emission requirements to which vehicle is designed",
    0x60: "PIDs supported [61-80]",
    0x61: "Driver's demand engine - percent torque",
    0x62: "Actual engine - percent torque",
    0x63: "Engine reference torque",
    0x64: "Engine percent torque data",
    0x65: "Auxiliary input / output supported",
    0x66: "Mass air flow sensor",
    0x67: "Engine coolant temperature",
    0x68: "Intake air temperature",
    0x69: "Commanded EGR and EGR error",
    0x6A: "Commanded diesel intake air flow control",
    0x6B: "EGR temperature",
    0x6C: "Commanded throttle actuator control and relative throttle position",
    0x6D: "Fuel pressure control system",
    0x6E: "Injection pressure control system",
    0x6F: "Turbocharger compressor inlet pressure",
    0x70: "Boost pressure control",
    0x71: "Variable geometry turbo control",
    0x72: "Wastegate control",
    0x73: "Exhaust pressure",
    0x74: "Turbocharger RPM",
    0x75: "Turbocharger temperature",
    0x76: "Turbocharger temperature",
    0x77: "Charge air cooler temperature",
    0x78: "Exhaust gas recirculation temperature Bank 1",
    0x79: "Exhaust gas recirculation temperature Bank 2",
    0x7A: "DPF Differential pressure",
    0x7B: "DPF",
    0x7C: "DPF Temperature",
    0x7D: "NOx NTE control area status",
    0x7E: "NOx NTE Control Area Status",
    0x7F: "Engine run time",
    #anything after this is useless for now
}



df = pd.DataFrame(pd.read_csv("logs/obd2_log20250606_142756.csv"))

df["Timestamp"] = pd.to_datetime(df["Timestamp"],format="%Y-%m-%d %H:%M:%S.%f")
fig, ax1 = plt.subplots()
# df.plot(ax=ax1,x="Timestamp")
# ax1.set_xlim(0, df.shape[0])

ax2 = ax1.twinx()
# ax1.set_xticklabels(df["Timestamp"])
# ax1.set_xlabel("Time")
# df["0xc"].plot(ax=ax1, label=OBD_PIDS[int("0xc",16)], color="blue",rot=45,grid=True)
df.plot(ax=ax1,x="Timestamp",y="0xc", label=OBD_PIDS[int("0xc",16)], color="blue",rot=45,grid=True)
df.plot(ax=ax2,x="Timestamp",y="0xd", label=OBD_PIDS[int("0xd",16)], color="orange",rot=45,grid=True)
# ax1.xaxis.set_major_locator(plt.MaxNLocator(20))  # Limit number of x-ticks
# df["0x11"].plot(ax=ax2, kind="line", label=OBD_PIDS[int("0x11",16)], color="orange",rot=45)
fig.legend(loc='upper right', bbox_to_anchor=(1, 1), bbox_transform=ax1.transAxes)
plt.show()